name: john-site
description: Run a custom shell script for markdown conversion.
inputs:
  source:
    description: 'Markdown source directory'
    required: true
  destination:
    description: 'HTML output directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Convert Markdown to HTML
      run: convert.sh "${{ inputs.src }}" "${{ inputs.dest }}"
      shell: bash
