name: john-site
description: Run a custom shell script for markdown conversion.
inputs:
  source:
    description: 'Markdown source directory'
    required: true
  destination:
    description: 'HTML output directory'
    required: true
  skeleton:
    description: 'Skeleton'
    required: false
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Convert Markdown to HTML
      env:
          GH_TOKEN: ${{ github.token }}
      run: convert.sh "${{ inputs.source }}" "${{ inputs.destination }}" "${{ inputs.skeleton }}"
      shell: bash
